/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zafu_jason_permissiondemo_common_jnicommon_JniUserUtil */

#ifndef _Included_com_zafu_jason_permissiondemo_common_jnicommon_JniUserUtil
#define _Included_com_zafu_jason_permissiondemo_common_jnicommon_JniUserUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zafu_jason_permissiondemo_common_jnicommon_JniUserUtil
 * Method:    printFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_zafu_jason_permissiondemo_common_jnicommon_JniUserUtil_printFromJNI
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
